# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zapis',
            old_name='FK_Vrach',
            new_name='doctor_fk',
        ),
        migrations.RenameField(
            model_name='zapis',
            old_name='FK_People',
            new_name='people_fk',
        ),
        migrations.RemoveField(
            model_name='smena',
            name='time',
        ),
        migrations.RemoveField(
            model_name='zapis',
            name='talon',
        ),
        migrations.AddField(
            model_name='smena',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='vrach',
            name='interval_of_work',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='vrach',
            name='smena',
            field=models.ManyToManyField(to='all.Smena'),
        ),
        migrations.AddField(
            model_name='zapis',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
