# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrach',
            name='price_ferst',
            field=models.IntegerField(default=0, verbose_name='Цена первичного приема'),
        ),
        migrations.AddField(
            model_name='vrach',
            name='price_second',
            field=models.IntegerField(default=0),
        ),
    ]
